-- 2026-05-22: Content diversity engine.
--
-- ai_configs.content_pillars: 8 "angles" the AI rotates through, each
-- {id (slug), name, description}. Lazy-generated by an LLM when the
-- array is empty. Stored as JSONB so editing is just an UPDATE.
--
-- posts.pillar_id: which pillar produced this post. Used by the
-- anti-recency selector to weight gaps + exclude the last 2.
--
-- posts.image_ref: which image was attached. Either a media_library
-- UUID (as text — JSONB-free since we never query into it) or the
-- literal "generated" for Gemini-synthesized images that aren't
-- (yet) reusable from the library. Used to exclude the last 10
-- images when picking the next one.

alter table public.ai_configs
  add column if not exists content_pillars jsonb not null default '[]'::jsonb;

alter table public.posts
  add column if not exists pillar_id text,
  add column if not exists image_ref text;

-- For the anti-recency lookup we always read by ai_config_id ordered
-- by created_at DESC limit 20 — a partial index on (ai_config_id,
-- created_at desc) where pillar_id is not null keeps that read cheap
-- even as posts grow.
create index if not exists posts_pillar_recency_idx
  on public.posts (ai_config_id, created_at desc)
  where pillar_id is not null;
